rule lvt_locker: critical {
  meta:
    description = "Ransomware phrases used by LVT Locker"

  strings:
    $a  = "By LVT LOCKER"
    $b  = "Your computers and servers"
    $c  = "servers are encrypted"
    $d  = "backups are deleted"
    $e  = "strong encryption algorithms"
    $f  = "no one has yet"
    $g  = "been able to decrypt"
    $h  = "decrypt their files"
    $i  = "without our participation"
    $j  = "only way to decrypt"
    $k  = "decrypt your files is"
    $l  = "is to purchase a"
    $m  = "universal decoder from"
    $n  = "will restore all"
    $o  = "the encrypted data"
    $p  = "and your network"
    $q  = "Follow our instructions"
    $r  = "you will recover"
    $s  = "all yourl data"
    $aa = "1) Pay 0.0"
    $ab = "bitcoin to"
    $ac = "Send us message"
    $ad = "with tranaction id and"
    $ae = "your personal key"
    $af = "README_lvt"
    $ag = "Launch decryptor"
    $ah = "which our support will"
    $ai = "send you through email"
    $aj = "We value our reputation"
    $ak = "we will not do our work"
    $al = "nobody will pay us"
    $am = "is not in our interests"
    $an = "our decryption software"
    $ao = "tested by time"
    $ap = "will decrypt all"
    $aq = "all your data"
    $ba = "DO NOT TRY TO"
    $bc = "TRY TO RECOVER ANY"
    $bd = "RECOVER ANY FILES"
    $be = "ANY FILES YOURSELF"
    $bf = "WE WILL NOT BE ABLE"
    $bg = "ABLE TO RESTORE"
    $bh = "TO RESTORE THEM"

    $not_sonar  = "Copyright (C) 2008-2013 SonarSource"
    $not_sonar2 = "mailto:contact AT sonarsource DOT com"
    $not_sonar3 = "SonarQube is free software; you can redistribute it and/or"

  condition:
    filesize < 2MB and 5 of them and none of ($not*)
}
