issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/malcontent:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/malcontent/.github/workflows/(version|release).yaml@.*

permissions:
  contents: write
  pull_requests: write
