# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Image digest update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions: {}

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: github.repository == 'chainguard-dev/malcontent'

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            cgr.dev:443
            fulcio.sigstore.dev:443
            github.com:443
            octo-sts.dev:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: chainguard-dev/actions/setup-gitsign@0cba302c40fce067ec0d39f1d91b10580d4b06b0

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: digestabot

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        # zizmor: ignore[artipacked] - credentials needed for digestabot to push and create PRs
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - uses: chainguard-dev/digestabot@afe360aa3b0c29d88844138e8fa0349384398967 # v1.3.1
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          include-files: ".github/workflows/*.yaml"
