# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Code Style

env:
  CGO_ENABLED: "1"
  GO_RELEASE: "go-1.26"
  YARA_X_RELEASE: "1.17.0"

permissions: {}

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  yrcompile:
    name: check yr compile
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            dl.google.com:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run make yara-x-compile
        run: |
          make yara-x-compile
          ret=$?
          if [[ $ret -ne 0 ]]; then
            echo "Rule compilation failed; address findings and commit the changes"
            exit 1
          fi

  yrfmt:
    name: check yr fmt
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            dl.google.com:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run make yara-x-fmt
        run: |
          make yara-x-fmt
          if [[ -n $(git status -s) ]]; then
            echo "Rule files updated; please run 'make yara-x-fmt' locally and commit the changes"
            exit 1
          fi

  gofmt:
    name: check gofmt
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            dl.google.com:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          check-latest: true

      - uses: chainguard-dev/actions/gofmt@05fbd381f7c158bd33c9bbf3a28f67852269fdf8 # main
        with:
          args: -s

  goimports:
    name: check goimports
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            dl.google.com:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          check-latest: true

      - uses: chainguard-dev/actions/goimports@05fbd381f7c158bd33c9bbf3a28f67852269fdf8 # main

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    container:
      image: cgr.dev/chainguard/wolfi-base:latest@sha256:9a74366aa10eff2bf14dab0948123bd2c51703e1c553a73740ef687f723aecf4
      options: >-
        --cap-add DAC_OVERRIDE
        --cap-add SETGID
        --cap-add SETUID
        --cap-drop ALL
        --cgroupns private
        --cpu-shares=4096
        --memory-swappiness=0
        --security-opt no-new-privileges
        --ulimit core=0
        --ulimit nofile=4096:4096
        --ulimit nproc=4096:4096
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add curl findutils gcc git "${GO_RELEASE}" make nodejs pkgconf "yara-x~${YARA_X_RELEASE}"

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Trust repository
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Run golangci-lint
        run: |
          make golangci-lint-lint
